CREATE TABLE users (
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(256) NOT NULL,
    reg_no VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL,
    pwd VARCHAR(256) NOT NULL
);